[build]
  command = "echo \"Publishing prebuilt Hugo output from public/\""
  publish = "public"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = false

[[redirects]]
  from = "/basilisk/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en/basilisk/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/pl/basilisk/"
  to = "/pl/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/basilisk/"
  to = "/fr/"
  status = 301
  force = true
